#!/usr/bin/env python3

from sys import argv
from math import sqrt

def read_test_file(file_name):
    with open(file_name, "r", encoding="utf-8") as file:
        number = int(file.readline().strip())

    return [number]

def find_numbers(n):
    for i in range(1, n):
        if n == ((n // i) * i):
            print("{}={}*{}".format(n, (n // i), i))
            break

def factors(ls):
    for i in ls:
        find_numbers(i)

if len(argv) == 2:
    factors(read_test_file(argv[1]))

