#!/bin/bash

check_factor() {
    if [[ $# -ne 2 ]]; then
        echo "Error: expected 2 arguments, got $#"
        exit 1
    fi
    p=$1
    q=$2
    echo "$p*$q"
}

if [[ $# -ne 1 ]]; then
    echo 'Usage: factors <file>'
    exit 1
fi

while read i; do
    factors=$(factor "$i")
    arr=($factors)
    p=${arr[-2]}
    q=${arr[-1]}
    check_factor "$p" "$q"
done < "$1"
