#!/bin/bash

check_factor() {
    if [[ $# -ne 2 ]]; then
        args=("$@")
        p=${args[0]}
        q=${args[1]}
    else
        p=$1
        q=$2
    fi

    if (( q > p )); then
        numcp=$p
        p=$q
        q=$numcp
    fi

    echo "$p*$q"
}

if [[ $# -ne 1 ]]; then
    echo 'Usage: factors <file>'
    exit 1
else
    while read i; do
        factors=$(factor "$i")
        arr=($factors)
        p=${arr[-2]}
        q=${arr[-1]}
        check_factor "$p" "$q"
    done < "$1"
fi

