#!/usr/bin/env python3

from sys import argv
from math import sqrt

def read_test_file(file_name):
    with open(file_name, "r", encoding="utf-8") as file:
        lines = file.readlines()

    number_to_factor = []

    for line in lines:
        number_to_factor.append(int(line))

    return number_to_factor[0]

def is_prime(n):
    if n < 2:
        return False
    elif n == 2:
        return True
    elif n % 2 == 0:
        return False
    else:
        for i in range(3, int(sqrt(n))+1, 2):
            if n % i == 0:
                return False
        return True

def find_numbers(n):
    for i in range(2, n):
        if n % i == 0 and is_prime(i) and is_prime(n // i):
            print("{}={}*{}".format(n, i, n // i))
            break

def factors(ls):
    for i in ls:
        find_numbers(i)

if len(argv) == 2:
    n = read_test_file(argv[1])
    find_numbers(n)
