#!/usr/bin/env python3

from sys import argv
from math import sqrt

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

def factorize_number(n):
    for i in range(2, int(sqrt(n)) + 1):
        if n % i == 0 and is_prime(i) and is_prime(n // i):
            print("{}={}*{}".format(n, i, n // i))
            return

def factorize_file(file_name):
    with open(file_name, "r", encoding="utf-8") as file:
        n = int(file.readline().strip())
    factorize_number(n)

if len(argv) == 2:
    factorize_file(argv[1])
